### ISSUE TITLE
Getting Jackson error when running connector in Mule project via Mule Studio

### ISSUE THREAD

**Issue by eebbesen** [eebbesen/car2go-connector#2]
Not really an issue with this repo, but with using this connector in a Mule flow (https://github.com/eebbesen/car2go-connector_example is what's giving me problems).  Not sure if this repo's contents need modification or just clients using it.  Please note that the functional test for this application (the one that actually queries from the real Car2Go API) is operational and error-free.

Getting Jackson error when running connector via Mule Studio.  Everything works fine when running functional tests in this application (via Eclipse and Maven).  Need to figure out how to run this with Mule 3.7 CE or if there are just incompatibilities that cannot be resolved.

```
ERROR 2017-03-19 20:37:34,592 [[car2go-connector_user].HTTP_Listener_Configuration.worker.01] org.mule.exception.DefaultMessagingExceptionStrategy: 
********************************************************************************
Message               : com.fasterxml.jackson.databind.ObjectReader.forType(Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/ObjectReader; (java.lang.NoSuchMethodError). Message payload is of type: NullPayload
Type                  : org.mule.api.MessagingException
Code                  : MULE_ERROR--2
JavaDoc               : http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html
Payload               : {NullPayload}
********************************************************************************
Exception stack is:
1. com.fasterxml.jackson.databind.ObjectReader.forType(Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/ObjectReader; (java.lang.NoSuchMethodError)
  com.fasterxml.jackson.jaxrs.base.ProviderBase:796 (null)
2. com.fasterxml.jackson.databind.ObjectReader.forType(Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/ObjectReader; (java.lang.NoSuchMethodError). Message payload is of type: NullPayload (org.mule.api.MessagingException)
  org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor:32 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)
********************************************************************************
Root Exception stack trace:
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectReader.forType(Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/ObjectReader;
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:796)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:264)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:234)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:154)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1124)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:851)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:783)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:111)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:399)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:108)
	at com.humegatech.Car2GoslingClientImpl.getLocations(Car2GoslingClientImpl.java:31)
	at com.humegatech.mule.modules.car2go.Car2GoConnector.getLocations(Car2GoConnector.java:19)
	at com.humegatech.mule.modules.car2go.generated.processors.GetLocationsMessageProcessor$1.process(GetLocationsMessageProcessor.java:106)
	at com.humegatech.mule.modules.car2go.generated.adapters.Car2GoConnectorProcessAdapter$1.execute(Car2GoConnectorProcessAdapter.java:36)
	at com.humegatech.mule.modules.car2go.generated.processors.GetLocationsMessageProcessor.doProcess(GetLocationsMessageProcessor.java:92)
	at org.mule.devkit.processor.DevkitBasedMessageProcessor.process(DevkitBasedMessageProcessor.java:88)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:85)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:56)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:94)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:56)
	at org.mule.processor.AsyncInterceptingMessageProcessor.process(AsyncInterceptingMessageProcessor.java:102)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:94)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:56)
	at org.mule.construct.DynamicPipelineMessageProcessor.process(DynamicPipelineMessageProcessor.java:55)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:85)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:56)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:94)
	at org.mule.processor.BlockingProcessorExecutor.execute(Blocki...
********************************************************************************
```

**Comment by eebbesen** [comment]
https://support.mulesoft.com/s/article/ka434000000TOZvAAO/How-to-override-library-dependencies-in-a-custom-connector

Not sure if this will help since the connector doesn't really seem to have a problem (works when run via JUnit), but the application using the connector.

**Comment by eebbesen** [comment]
Solved by using the fine-grained classloader on the sample application: https://docs.mulesoft.com/mule-user-guide/v/3.8/fine-grain-classloader-control#configuring-the-fine-grain-classloader
